// Generates rover/src/navi_shaper/test/ik_feasibility_golden.json, the fixture
// SP10's shaper is checked against.
//
// Deliberately NOT a CMake target, for the reasons golden_harness_242.cpp
// gives: it is a code generator, not a test, so keeping it out of the package
// build means it can never break the build, never install, and never
// accidentally link the 2.41 model. Build and run it by hand:
//
//   g++ -std=c++17 -O2 -w \
//     -I/home/ole/star/Navi/sim/src/navi_sim_ik/vendor242 \
//     -I/home/ole/star/Navi/sim/src/navi_sim_ik/include \
//     /home/ole/star/Navi/sim/src/navi_sim_ik/test/feasibility_harness_242.cpp \
//     /home/ole/star/Navi/sim/src/navi_sim_ik/vendor242/*.cpp \
//     -o /tmp/feasibility_harness_242 \
//   && /tmp/feasibility_harness_242 \
//     > /home/ole/star/Navi/rover/src/navi_shaper/test/ik_feasibility_golden.json
//
// It compiles the SAME vendored sources the sim links, with the SAME Asterope
// parameters, so what it prints is the model's own behaviour and not a
// transcription of anything. Regenerate it whenever vendor242/ or
// asterope_params.hpp changes - which, both being frozen, should be never
// without a deliberate re-vendor.

#include <cmath>
#include <cstdio>

#include "kinematics.h"
#include "navi_sim_ik/asterope_params.hpp"

namespace
{

struct Command
{
  double vx;
  double vy;
  double wz;
  const char * name;
};

// Chosen to span everything this rover is asked to do: the manual cap
// (0.05 / 0.1) and each autonomy stage from spec section 10, the wz ceiling,
// the reverse floor from section 5, both crab directions, both turn
// directions, and the three degenerate geometries a clamp meets most often
// (straight, pure crab, pure point turn).
constexpr Command kCommands[] = {
  {0.05, 0.0, 0.0, "straight_manual"},
  {0.05, 0.0, 0.1, "arc_left_manual"},
  {0.05, 0.0, -0.1, "arc_right_manual"},
  {0.0, 0.0, 0.1, "point_turn_left"},
  {0.0, 0.0, -0.1, "point_turn_right"},
  {0.05, 0.0, 0.05, "arc_left_shallow"},
  {0.05, 0.0, -0.05, "arc_right_shallow"},
  {0.02, 0.0, 0.1, "arc_left_tight"},
  {0.15, 0.0, 0.1, "stage2_arc"},
  {0.15, 0.0, 0.0, "stage2_straight"},
  {0.30, 0.0, 0.20, "stage3_arc"},
  {0.45, 0.0, 0.40, "stage4_arc_at_ceiling"},
  {0.45, 0.0, 0.0, "stage4_straight"},
  {0.0, 0.05, 0.0, "crab_left"},
  {0.0, -0.05, 0.0, "crab_right"},
  {0.05, 0.02, 0.07, "combined"},
  {-0.15, 0.0, 0.0, "reverse_floor"},
  {0.02, 0.0, 0.0, "straight_slow"},
  {0.0, 0.0, 0.0, "zero"},
};

constexpr int kCommandCount = sizeof(kCommands) / sizeof(kCommands[0]);

// 400 steps = 24 s. Every transition measured settles well inside that; the
// slowest observed is 56 ticks.
constexpr int kSettleSteps = 400;
constexpr int kTransitionSteps = 300;

// 20 ticks = 1.2 s of an exact-zero twist, the supervisor's stop / estop /
// deadman stream. Long enough that any real steering toward the point turn
// would be plainly visible (the sweep takes 26 ticks and would be a third done
// by now); measured, the drift is exactly 0.0, because Retain Translation
// never lets the zeros reach the ICR controller at all.
constexpr int kZeroHoldSteps = 20;

// beta_next stops changing entirely once the geometry is reached - the model
// is deterministic and has no noise, so this is an exact test, not a
// threshold on a decaying quantity.
constexpr double kSettledEpsilon = 1e-7;

void configure(ExtU_kinematics_T & in)
{
  in.TS = navi_sim_ik::kIkTimestepSeconds;
  in.beta_dot_max = navi_sim_ik::kBetaDotMax;
  in.beta_ddot_max = navi_sim_ik::kBetaDdotMax;
  in.acceleration_factor = navi_sim_ik::kAccelerationFactor;
  for (int i = 0; i < 8; ++i) {
    in.hParams[i] = navi_sim_ik::kAsteropeHParams[i];
  }
}

// Closed loop with the model's own outputs, exactly as SimIkStepper does: a
// kinematic simulation has no encoders, so what the model commanded this tick
// is what it measures next tick.
void feedback(ExtU_kinematics_T & in, const ExtY_kinematics_T & out)
{
  for (int w = 0; w < 4; ++w) {
    in.beta_hat[w] = out.beta_next[w];
    in.beta_dot_hat[w] = out.Beta_dot[w];
  }
}

void drive(kinematics & model, ExtU_kinematics_T & in, const Command & c, int steps)
{
  in.VX_out = c.vx;
  in.VY_out = c.vy;
  in.U = c.wz;   // rad/s, ROS sign - no negation, no degrees
  for (int s = 0; s < steps; ++s) {
    model.setExternalInputs(&in);
    model.step();
    feedback(in, model.getExternalOutputs());
  }
}

}  // namespace

int main()
{
  std::printf("{\n");
  std::printf("  \"_comment\": \"Generated by sim/src/navi_sim_ik/test/"
    "feasibility_harness_242.cpp from the real 2.42 model. Do not hand-edit.\",\n");
  std::printf("  \"ik_timestep_s\": %.17g,\n", navi_sim_ik::kIkTimestepSeconds);
  std::printf("  \"beta_dot_max\": %.17g,\n", navi_sim_ik::kBetaDotMax);

  std::printf("  \"hparams\": [");
  for (int i = 0; i < 8; ++i) {
    std::printf("%s%.17g", i ? ", " : "", static_cast<double>(navi_sim_ik::kAsteropeHParams[i]));
  }
  std::printf("],\n");

  // --- the static map: what geometry each command settles to ---------------
  std::printf("  \"settled\": [\n");
  for (int i = 0; i < kCommandCount; ++i) {
    kinematics model;
    model.initialize();
    ExtU_kinematics_T in{};
    configure(in);
    drive(model, in, kCommands[i], kSettleSteps);
    const ExtY_kinematics_T & o = model.getExternalOutputs();
    std::printf("    {\"name\": \"%s\", \"cmd\": [%.17g, %.17g, %.17g], "
      "\"input_icr\": [%.17g, %.17g], \"beta_next\": [%.17g, %.17g, %.17g, %.17g], "
      "\"eta_dot_constrained\": [%.17g, %.17g, %.17g]}%s\n",
      kCommands[i].name, kCommands[i].vx, kCommands[i].vy, kCommands[i].wz,
      o.input_ICR[0], o.input_ICR[1],
      o.beta_next[0], o.beta_next[1], o.beta_next[2], o.beta_next[3],
      o.eta_dot_constrained[0], o.eta_dot_constrained[1], o.eta_dot_constrained[2],
      (i + 1 < kCommandCount) ? "," : "");
  }
  std::printf("  ],\n");

  // --- the dynamics: what every transition between them costs ---------------
  // This is the half that cannot be computed in Python (the model routes the
  // ICR through an optimiser with a latched indirect mode), so it is measured.
  std::printf("  \"transitions\": [\n");
  bool first = true;
  for (int i = 0; i < kCommandCount; ++i) {
    for (int j = 0; j < kCommandCount; ++j) {
      if (i == j) {
        continue;
      }
      kinematics model;
      model.initialize();
      ExtU_kinematics_T in{};
      configure(in);
      drive(model, in, kCommands[i], kSettleSteps);

      in.VX_out = kCommands[j].vx;
      in.VY_out = kCommands[j].vy;
      in.U = kCommands[j].wz;

      int settle_tick = -1;
      double travel = 0.0;
      double yaw = 0.0;
      for (int s = 0; s < kTransitionSteps; ++s) {
        model.setExternalInputs(&in);
        model.step();
        const ExtY_kinematics_T & o = model.getExternalOutputs();
        double worst = 0.0;
        for (int w = 0; w < 4; ++w) {
          const double d = std::fabs(o.beta_next[w] - in.beta_hat[w]);
          if (d > worst) {
            worst = d;
          }
        }
        feedback(in, o);
        if (settle_tick < 0) {
          // Ground covered while the geometry is still in transit - the
          // quantity the shaper's gain actually reduces.
          travel += std::hypot(o.eta_dot_constrained[0], o.eta_dot_constrained[1]) *
            navi_sim_ik::kIkTimestepSeconds;
          yaw += o.eta_dot_constrained[2] * navi_sim_ik::kIkTimestepSeconds;
          if (worst < kSettledEpsilon) {
            settle_tick = s;
          }
        }
      }
      std::printf("%s    {\"from\": \"%s\", \"to\": \"%s\", \"settle_ticks\": %d, "
        "\"travel_m\": %.17g, \"yaw_rad\": %.17g}",
        first ? "" : ",\n", kCommands[i].name, kCommands[j].name, settle_tick, travel, yaw);
      first = false;
    }
  }
  std::printf("\n  ],\n");

  // --- Retain Translation: what a STOP does to the geometry -----------------
  // The sweep above drives each `from` command on a freshly initialize()d
  // model, which cannot see '<S1>/Retain Translation' (kinematics.cpp:798-824)
  // at all: that block only fires once UnitDelay_DSTATE holds a non-zero
  // command. On a full-zero twist it feeds the ICR Position Controller from
  // the LAST NON-ZERO command instead of from the zeros, so the chassis holds
  // the geometry it had rather than steering to the point turn.
  //
  // This section makes that observable. For each ordered pair it settles
  // `from`, drives kZeroHoldSteps of exact zeros, and only then commands `to`.
  // If Retain Translation behaves as read, these settle_ticks match the
  // fresh-model transition i->j (the stop changed nothing), and NOT the
  // transition zero->j. That is the fixture the shaper's corrected zero policy
  // is answerable to: the shaper must keep believing in `from`'s geometry
  // across the stop, exactly as the model does.
  std::printf("  \"retained\": [\n");
  first = true;
  for (int i = 0; i < kCommandCount; ++i) {
    if (kCommands[i].vx == 0.0 && kCommands[i].vy == 0.0 && kCommands[i].wz == 0.0) {
      continue;   // "zero" as an origin has nothing to retain
    }
    for (int j = 0; j < kCommandCount; ++j) {
      if (i == j) {
        continue;
      }
      kinematics model;
      model.initialize();
      ExtU_kinematics_T in{};
      configure(in);
      drive(model, in, kCommands[i], kSettleSteps);

      // Capture the geometry the stop is supposed to preserve.
      const double icr_before[2] = {
        model.getExternalOutputs().input_ICR[0],
        model.getExternalOutputs().input_ICR[1],
      };

      const Command zero{0.0, 0.0, 0.0, "zero"};
      drive(model, in, zero, kZeroHoldSteps);
      const ExtY_kinematics_T & z = model.getExternalOutputs();
      const double icr_drift = std::hypot(z.input_ICR[0] - icr_before[0],
        z.input_ICR[1] - icr_before[1]);

      in.VX_out = kCommands[j].vx;
      in.VY_out = kCommands[j].vy;
      in.U = kCommands[j].wz;

      int settle_tick = -1;
      double travel = 0.0;
      for (int s = 0; s < kTransitionSteps; ++s) {
        model.setExternalInputs(&in);
        model.step();
        const ExtY_kinematics_T & o = model.getExternalOutputs();
        double worst = 0.0;
        for (int w = 0; w < 4; ++w) {
          const double d = std::fabs(o.beta_next[w] - in.beta_hat[w]);
          if (d > worst) {
            worst = d;
          }
        }
        feedback(in, o);
        if (settle_tick < 0) {
          travel += std::hypot(o.eta_dot_constrained[0], o.eta_dot_constrained[1]) *
            navi_sim_ik::kIkTimestepSeconds;
          if (worst < kSettledEpsilon) {
            settle_tick = s;
          }
        }
      }
      std::printf("%s    {\"from\": \"%s\", \"to\": \"%s\", \"settle_ticks\": %d, "
        "\"travel_m\": %.17g, \"icr_drift_during_stop\": %.17g}",
        first ? "" : ",\n", kCommands[i].name, kCommands[j].name, settle_tick,
        travel, icr_drift);
      first = false;
    }
  }
  std::printf("\n  ]\n}\n");
  return 0;
}
