"""The pure Python geometry map, against the real 2.42 model's own output.

The fixture is generated by sim/src/navi_sim_ik/test/feasibility_harness_242.cpp
from the vendored model. If this test fails, either ik_geometry.py drifted or
someone re-vendored the IK without regenerating the fixture; in both cases the
feasibility clamp is no longer clamping against the model the wheels obey.
"""
import json
import math
import pathlib

import pytest

from navi_shaper import ik_geometry as g
from navi_shaper.shaper import HOLD_TICKS, hold_ticks_for

GOLDEN = json.loads(
    (pathlib.Path(__file__).parent / "ik_feasibility_golden.json").read_text())


def test_fixture_is_complete():
    assert len(GOLDEN["settled"]) == 19
    assert len(GOLDEN["transitions"]) == 19 * 18
    assert len(GOLDEN["retained"]) == 18 * 18
    assert all(t["settle_ticks"] >= 0 for t in GOLDEN["transitions"]), \
        "a transition did not settle within 300 ticks - the hold table is unsafe"
    assert all(t["settle_ticks"] >= 0 for t in GOLDEN["retained"])


def test_constants_match_the_model():
    assert g.IK_TIMESTEP_S == GOLDEN["ik_timestep_s"]
    assert g.BETA_DOT_MAX == GOLDEN["beta_dot_max"]
    assert list(g.HPARAMS) == GOLDEN["hparams"]


@pytest.mark.parametrize("row", GOLDEN["settled"], ids=lambda r: r["name"])
def test_icr_is_bit_exact(row):
    got = g.commanded_icr(*row["cmd"])
    assert got[0] == pytest.approx(row["input_icr"][0], abs=1e-12)
    assert got[1] == pytest.approx(row["input_icr"][1], abs=1e-12)


@pytest.mark.parametrize("row", GOLDEN["settled"], ids=lambda r: r["name"])
def test_steering_angles_are_bit_exact_modulo_pi(row):
    got = g.steering_angles(*g.commanded_icr(*row["cmd"]))
    for mine, theirs in zip(got, row["beta_next"]):
        assert g.angle_distance(mine, theirs) == pytest.approx(0.0, abs=1e-12)


def test_hold_table_bounds_every_measured_transition():
    """The safety property of the whole sub-project.

    For every transition the real model performs, the hold window the shaper
    would open must be at least as long as the model actually takes. An
    under-estimate means the shaper releases the gain while the wheels are
    still sweeping - which is precisely the failure it exists to prevent.
    """
    by_name = {r["name"]: tuple(r["cmd"]) for r in GOLDEN["settled"]}
    worst = []
    for t in GOLDEN["transitions"]:
        d = g.command_distance(by_name[t["from"]], by_name[t["to"]])
        budget = hold_ticks_for(d)
        assert budget >= t["settle_ticks"], (
            f"{t['from']} -> {t['to']}: dBeta={d:.3f} budget={budget} "
            f"but the model took {t['settle_ticks']} ticks")
        worst.append(budget - t["settle_ticks"])
    # Conservative, but not absurdly so: a table that just returned a huge
    # constant would pass the assertion above and cripple the rover. The
    # measured mean slack over all 342 transitions is 28.71 ticks, dominated by
    # the two large-dBeta buckets whose medians (17 and 20) sit far below their
    # maxima (56 and 51). That 28.71 is where the < 50 threshold comes from.
    assert sum(worst) / len(worst) < 50, "the hold table is far more conservative than needed"


def test_a_stop_does_not_move_the_geometry():
    """'<S1>/Retain Translation', kinematics.cpp:798-824.

    A full-zero twist does not reach the ICR Position Controller: the block
    substitutes UnitDelay_DSTATE, the last non-zero command, so the chassis
    holds the geometry it had. This is the model property the shaper's zero
    short-circuit is built on - it relays the stop untouched but keeps its
    belief about where the wheels are.
    """
    assert all(r["icr_drift_during_stop"] == 0.0 for r in GOLDEN["retained"]), \
        "a stop moved the ICR - Retain Translation is not behaving as read"


def test_the_hold_table_bounds_transitions_taken_through_a_stop():
    """The safety property again, on the path the shaper is actually used on.

    Nav2 does not step straight from one command to the next; it stops, then
    turns. The shaper must therefore size its hold from the retained geometry,
    not from the zeros - so the same command_distance(from, to) that bounds the
    fresh-model sweep must also bound the drive-stop-turn sweep.
    """
    by_name = {r["name"]: tuple(r["cmd"]) for r in GOLDEN["settled"]}
    for t in GOLDEN["retained"]:
        d = g.command_distance(by_name[t["from"]], by_name[t["to"]])
        assert hold_ticks_for(d) >= t["settle_ticks"], (
            f"{t['from']} -> stop -> {t['to']}: dBeta={d:.3f} "
            f"budget={hold_ticks_for(d)} but the model took {t['settle_ticks']}")


def test_a_stop_then_a_point_turn_is_a_full_size_transition():
    """The drive-stop-turn sequence of ruling 5(a), pinned as a number.

    Drive straight, stop, turn in place. If the shaper cleared its belief on
    the stop it would compute dBeta = 0 here, open no hold, and pass a
    full-speed point turn into the largest geometry change the chassis can be
    asked to make. The model's own cost says otherwise.
    """
    row = next(r for r in GOLDEN["retained"]
               if r["from"] == "straight_manual" and r["to"] == "point_turn_left")
    assert row["settle_ticks"] >= 20, \
        "a stop did not preserve the straight geometry"
    assert row["travel_m"] == pytest.approx(0.0441, abs=0.005)
    # And the shaper's own view of it, from the pure map, agrees.
    assert g.command_distance((0.05, 0.0, 0.0), (0.0, 0.0, 0.1)) == \
        pytest.approx(0.8475, abs=0.001)


def test_resuming_the_same_command_after_a_stop_costs_nothing():
    """The corollary, and why the corrected policy is cheap as well as safe."""
    for name in ("straight_manual", "arc_left_manual", "point_turn_left"):
        rows = [r for r in GOLDEN["retained"] if r["from"] == name and r["to"] == name]
        assert not rows, "i == j is skipped by construction"
    row = next(r for r in GOLDEN["retained"]
               if r["from"] == "straight_manual" and r["to"] == "stage2_straight")
    # Same geometry family, different speed: the wheels barely move.
    assert row["settle_ticks"] <= HOLD_TICKS[0][1]


def test_the_rpp_regime_needs_no_holding():
    """Spec section 5: a slowly moving ICR is the regime the IK never clips."""
    by_name = {r["name"]: tuple(r["cmd"]) for r in GOLDEN["settled"]}
    small = [t for t in GOLDEN["transitions"]
             if g.command_distance(by_name[t["from"]], by_name[t["to"]]) <= g.ONE_TICK_BETA]
    assert small, "the sweep contains no small-step transitions to check"
    assert max(t["settle_ticks"] for t in small) <= HOLD_TICKS[0][1]


def test_a_straight_command_is_not_straight():
    """Documented so it cannot be silently 'fixed' later.

    delta = 0.005 makes a wz = 0 command read as a 0.005 rad/s left turn, so at
    the 0.05 m/s manual cap the chassis steers a 9.87 m arc and yaws at about
    0.005 rad/s. No shaper obeying the never-larger rule can correct this - it
    would have to increase |wz|. It is reported on /ik_feasibility instead, and
    is SP12 yard-tuning input.
    """
    row = next(r for r in GOLDEN["settled"] if r["name"] == "straight_manual")
    assert row["input_icr"][1] == pytest.approx(9.8688, abs=1e-3)
    assert row["eta_dot_constrained"][2] == pytest.approx(0.00496, abs=1e-4)
    assert row["eta_dot_constrained"][2] != 0.0
